#!/usr/bin/env bash

feature_branch="$1"

if [[ -z "$feature_branch" ]]
then
    echo "You must input a branch to merge into current branch."
    exit 1
elif ! git show-ref --quiet "refs/heads/$feature_branch"
then
    echo "Branch '$feature_branch' does not exist."
    exit 1
fi

current_branch="$(git rev-parse --abbrev-ref HEAD)"
commit_message=$(git log --pretty=format:'%h %s' "HEAD..$feature_branch")

commit_message="Merge '$feature_branch' into '$current_branch'

Merge list:
${commit_message}"

git merge --no-ff -m "$commit_message" "$feature_branch"
